cache:
    directories:
        - $HOME/.composer/cache

git:
    depth: 1

install:
    - composer require --dev phpunit/phpunit squizlabs/php_codesniffer

language: php

notifications:
    email: false

php:
    - '7.0'
    - '7.1'
    - 'nightly'

script:
    - ./vendor/bin/phpcs --ignore=TraitIntTheSameFileTrait.php --report-full --standard=PSR2 src/ tests/
    - phpdbg -qrr ./vendor/phpunit/phpunit/phpunit

sudo: false
