install:
    - composer require --dev phpunit/phpunit squizlabs/php_codesniffer

language: php

notifications:
    email: false

php:
    - '7.0'
    - '7.1'
    - 'nightly'
    - 'hhvm'

script:
    - ./vendor/bin/phpcs --report-full --standard=PSR2 src/ tests/
    - ./vendor/bin/phpunit

sudo: false
